### PR TITLE
cleaned up charts

### PR DESCRIPTION
**Pull request by gitkent**
Cleaned up unwanted charts.

## References
https://github.com/wiremock/helm-charts/pull/43#issuecomment-2346074451

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [ ] Test coverage that demonstrates that the change works as expected
- [ ] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
@gitkent There is an issue with the index in gh-pages: the older versions 0.1.0 to 0.1.3 have a wrong link to download the file 
See https://github.com/wiremock/helm-charts/blob/gh-pages/index.yaml#L121-L148
Example: https://gitkent.github.io/helm-charts/wiremock-0.1.3.tgz

**Review by DanielFran — CHANGES_REQUESTED** [review]
@gitkent There is an issue with the index in gh-pages: the older versions 0.1.0 to 0.1.3 have a wrong link to download the file
See https://github.com/wiremock/helm-charts/blob/gh-pages/index.yaml#L121-L148
Example: https://gitkent.github.io/helm-charts/wiremock-0.1.3.tgz

v01.3 might be updated to use the release artifact, but the other 0.1.0, 0.1.1 and 0.1.2 need a new link

**Comment by gitkent** [comment]
> @gitkent There is an issue with the index in gh-pages: the older versions 0.1.0 to 0.1.3 have a wrong link to download the file See https://github.com/wiremock/helm-charts/blob/gh-pages/index.yaml#L121-L148 Example: https://gitkent.github.io/helm-charts/wiremock-0.1.3.tgz
> 
> v01.3 might be updated to use the release artifact, but the other 0.1.0, 0.1.1 and 0.1.2 need a new link

We will need another PR to fix that as the PR will need to merge into `gh-pages` branch not `master` branch. also we may have to retire version 0.1.0, 0.1.1 ad 0.1.2 since the older link we can get from github release is only 0.1.3 as in here: https://github.com/wiremock/helm-charts/releases.

**Comment by DanielFran** [comment]
@gitkent Probably it is easier to remove all links prior 0.1.3 version and just updated the link for 0.1.3

**Review by leeturner — APPROVED** [review]

**Pull request merged**
