### PR TITLE
Add securityContext to copy-responses init container

### LINKED ISSUE #42: Missing securityContext element in copy-responses containers
### Proposal

WireMock deployment failed while using the Helm chart on a cluster with FIPS compliant mode is enabled due to the missing securityContext parameter in `copy-responses` init container:
```yaml
        - name: copy-responses
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          command: ["bash", "-c", "cp  -rf /data/responses /home/wiremock/storage/__files"]
          volumeMounts:
            - mountPath: /data/responses
              name: responses-volume
            - mountPath: /home/wiremock/storage/__files
              name: responses-data
```

### Steps:
1. Set up FIPS compliant mode on the K8s cluster or configure the Pod Security Admission with `baseline` or `restricted`
2. Use `helm install` command as defined in the README.md

### Result:

```
Error creating: pods "wiremock-66c5f5ccd-ndhp2" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false must set securityContext.allowPrivilegeEscalation = false), ....
```

### References

- https://github.com/subigre/wiremock-helm-charts/blob/master/charts/wiremock/templates/deployment.yaml#L76-L77

### PR DESCRIPTION
**Pull request by subigre**
This PR adds the missing `securityContext` attribute on `copy-responses` similarly to how it is done on `wiremock` and `copy-mappings` containers

## References

Closes #42 

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

**Review by DanielFran — APPROVED** [review]
Good catch!

**Comment by subigre** [comment]
Just bumped the chart version that I forgot to do in the previous commit 😞
I wasn’t sure if I can also update the app version at the same time as WireMock version is `3.9.1` now, or if it is better to do it in a separate PR as it is not related to the initial scope?

**Comment by gitkent** [comment]
> Just bumped the chart version that I forgot to do in the previous commit 😞 I wasn’t sure if I can also update the app version at the same time as WireMock version is `3.9.1` now, or if it is better to do it in a separate PR as it is not related to the initial scope?

Leave app version as is. 

> Just bumped the chart version that I forgot to do in the previous commit 😞 I wasn’t sure if I can also update the app version at the same time as WireMock version is `3.9.1` now, or if it is better to do it in a separate PR as it is not related to the initial scope?

@subigre leave app version as is. For chart version can you please change to `1.1.0` as we want to follow semantic versioning with `<breaking-change>.<feature>.<bugfix>`

Adding a new fields in deployment is a feature. Thanks 😊

**Review by gitkent — CHANGES_REQUESTED** [review]
Please update version to 1.1.0

**Review by gitkent — APPROVED** [review]

**Review by gitkent — CHANGES_REQUESTED** [review]
Hi @subigre can you also please publish the chart with version 1.1.0, otherwise helm install will fail.

Thanks 😊

**Comment by subigre** [comment]
Hello @gitkent, to be honest, I didn’t understand why the charts are in the `master` branch.
I only used it with OCI registries so far, but isn’t automatically packaged and pushed by the use of `helm/chart-releaser-action` in your release workflow?

**Comment by subigre** [comment]
Done anyway

**Review by gitkent — APPROVED** [review]

**Comment by DanielFran** [comment]
@gitkent index has not been updated with the new version 1.1.0

**Comment by gitkent** [comment]
> @gitkent index has not been updated with the new version 1.1.0

@DanielFran  thanks for pointing out. Please review this https://github.com/wiremock/helm-charts/pull/45

**Comment by subigre** [comment]
It is already up to date in the gh-pages branches
https://github.com/wiremock/helm-charts/blob/gh-pages/index.yaml#L4-L31

What is the purpose of adding the `index.yaml` in the main branch as well? the chart-releaser tool already handles it for us by default?

**Comment by gitkent** [comment]
> It is already up to date in the gh-pages branches https://github.com/wiremock/helm-charts/blob/gh-pages/index.yaml#L4-L31
> 
> Trying to understand, what is the purpose of adding the `index.yaml` in the main branch as well? the chart-releaser tool already handles it for us by default?

@subigre you are right, chart-releaser action already updated index.yaml gh-pages branch but Github Pages is still pointing at master branch. I have updated Pages to point to gh-pages branch now. Hence no index.yaml and tar ball need to be updated into master branch. We will need to clean this up to avoid confusion.

FYI @DanielFran

**Pull request merged**
